# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24a08f0a332932341b9dcdb44425f1a0e651771088ff3e768a7eb579899d19222a7c951945ad617acb118bea4bbd4ddabd1d90095c024fe5a1c2145494540dcb

test:
  secret_key_base: cec7bb4fe83afa7c2405f87774b6911c352849aae56d899bfe4ec32d5146c42f827588199d88c64df915bc646cdaff51a8b5a25a085b5c7174ae55c494e7090c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
